name: Update Docker
on: [push]
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ssh-key: ${{ secrets.TEST_RUNNER_PRIVATE_SSH }}

      - name: Private actions checkout
        uses: daspn/private-actions-checkout@v2
        with:
          actions_list: '["aion-dk/build-and-push-action@v1.0.2"]'
          checkout_base_path: ./.github/actions
          ssh_private_key: ${{ secrets.ACTIONS_REPO_DEPLOY_TOKEN }}

      - name: 'Build and push docker image'
        uses: ./.github/actions/build-and-push-action
        with:
          image_name: voter-authorizer
          ecr_access_key_id: ${{ secrets.AWS_RW_ACCESS_KEY_ID }}
          ecr_secret_key: ${{ secrets.AWS_RW_SECRET_KEY }}
